name: Publish Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        # uses: actions/checkout@v5
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        # uses: actions/setup-python@v6
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        # uses: astral-sh/setup-uv@v5 v5.2.1
        uses: astral-sh/setup-uv@b5f58b2abc5763ade55e4e9d0fe52cd1ff7979ca
        with:
          enable-cache: true

      - name: Verify tools 1
        run: |
          uv --version
          uv run --frozen python --version
          sha256sum --version
          gh --version

      - name: Install dependencies
        run: uv sync --frozen --no-build --extra build --python "${{ matrix.python-version }}"

      - name: Verify build tools 2
        run: |
          uv run --frozen pyinstaller --version

      - name: Build Executable and Rename
        run: |
          uv run --frozen --no-build --python "${{ matrix.python-version }}" pyinstaller --clean AsdSte100Lookup.spec
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          VERSION=${{ github.ref_name }}
          
          mv dist/AsdSte100Lookup dist/AsdSte100Lookup-${VERSION}-${OS}-${ARCH}
          sha256sum dist/AsdSte100Lookup-${VERSION}-${OS}-${ARCH} > dist/AsdSte100Lookup-${VERSION}-${OS}-${ARCH}.sha256

      - name: Upload binaries to Release
        run: |
          VERSION=${{ github.ref_name }}

          gh release create ${VERSION} --title "${VERSION}" --generate-notes || true
          gh release upload ${VERSION} dist/AsdSte100Lookup-${VERSION}-* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
